### ISSUE TITLE
Clicking Item Name Does not Create a New Note

### ISSUE THREAD

**Issue by ticmain** [nybbles/obsidian-pocket#81]
I've set up a template and a folder for Pocket notes. 

But clicking the Pocket item title does not create a new note.

**Comment by yaogjim** [comment]
so do I

**Comment by AlexCaranha** [comment]
I was expecting that after syncing, every article will turn into a new note.

**Comment by nybbles** [comment]
> I was expecting that after syncing, every article will turn into a new note.

Please see #37.

**Comment by nybbles** [comment]
@ticmain I need more information. Can you open the dev console (i.e. using [these instructions](https://forum.obsidian.md/t/how-to-access-the-console/16703/2?u=nybbles)) after trying unsuccessfully to create a new note and post any errors/exceptions or logs that might seem relevant to the problem?

**Comment by nybbles** [comment]
I unfortunately don't have validation of user input in the settings for Pocket item note template or Pocket item note folder, so my hypothesis is that your settings are simply pointing at a template file or note folder that does not exist. It would be great to confirm that that is in fact what is happening, and then I could add some kind of validation there, or at least better error messages.

**Comment by yaogjim** [comment]
this is my console log:

> wrap-idb-value.js:150 Uncaught (in promise) DOMException: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.
    at Proxy.eval (eval at <anonymous> (app://obsidian.md/app.js:1:1362602), <anonymous>:30479:26)
    at Proxy.method (eval at <anonymous> (app://obsidian.md/app.js:1:1362602), <anonymous>:30564:25)
    at URLToPocketItemNoteIndex.eval (eval at <anonymous> (app://obsidian.md/app.js:1:1362602), <anonymous>:30914:22)
    at Generator.next (<anonymous>)
    at eval (eval at <anonymous> (app://obsidian.md/app.js:1:1362602), <anonymous>:28:71)
    at new Promise (<anonymous>)
    at __awaiter (eval at <anonymous> (app://obsidian.md/app.js:1:1362602), <anonymous>:24:12)
    at URLToPocketItemNoteIndex.lookupItemNoteForURL (eval at <anonymous> (app://obsidian.md/app.js:1:1362602), <anonymous>:30913:40)
    at eval (eval at <anonymous> (app://obsidian.md/app.js:1:1362602), <anonymous>:32101:48)
    at Generator.next (<anonymous>)

**Comment by ticmain** [comment]
@nybbles my apologies. I went away for a few days and am just getting back to this.

I updated to 0.6.1 today and the plugin now works as expected. Thank you for the fix!
